# Generated by Django 2.0 on 2020-06-15 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_medicine', models.BooleanField(default=False)),
                ('symptom_improvement', models.BooleanField(default=False)),
                ('compliance_medicine_comment', models.CharField(blank=True, max_length=30, null=True)),
                ('symptom_improvement_comment', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_code', models.CharField(max_length=30)),
                ('medicine_name', models.CharField(max_length=30)),
                ('dosis', models.FloatField(blank=True, null=True)),
                ('number_of_dosing', models.IntegerField(blank=True, null=True)),
                ('date_of_dosing', models.IntegerField(blank=True, null=True)),
                ('taking_method', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_date', models.DateTimeField(auto_now_add=True)),
                ('hospital_name', models.CharField(max_length=30, null=True)),
                ('hospital_web', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=5)),
                ('user_age', models.IntegerField()),
                ('user_sex', models.BooleanField(default=True)),
                ('user_pw', models.CharField(max_length=15)),
                ('user_photo', models.ImageField(blank=True, upload_to='')),
                ('family_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='health_bot.Family')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescription_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_bot.User'),
        ),
        migrations.AddField(
            model_name='appraisal',
            name='appraisal_medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine'),
        ),
    ]
