# Generated by Django 2.0 on 2020-06-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlap_ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_medicine_name', models.CharField(blank=True, max_length=100, null=True)),
                ('over_medicine_code', models.CharField(blank=True, max_length=30, null=True)),
                ('over_medicine_object_name', models.CharField(blank=True, max_length=100, null=True)),
                ('over_medicine_objcet_code', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pregnat_ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregnat_ingredient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_ingredient_code', models.CharField(blank=True, max_length=30, null=True)),
                ('pregnat_medicine_code', models.CharField(blank=True, max_length=30, null=True)),
                ('pregnat_medicine_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pregnat_manufacturer_name', models.CharField(blank=True, max_length=30, null=True)),
                ('pregnat_pbc_no', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_pbc_dt', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_incmp_grd', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_note', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_version', models.CharField(blank=True, max_length=100, null=True)),
                ('pregnat_pay', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
