# Generated by Django 2.0 on 2020-06-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0002_overlap_ban_pregnat_ban'),
    ]

    operations = [
        migrations.CreateModel(
            name='Overlap_caution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('over_caution_ingredient_name_A', models.CharField(blank=True, max_length=100, null=True)),
                ('over_caution_ingredient_code_A', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_medicine_code_A', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_medicine_name_A', models.CharField(blank=True, max_length=100, null=True)),
                ('over_caution_manufacturer_name_A', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_pay_A', models.CharField(blank=True, max_length=100, null=True)),
                ('over_caution_ingredient_name_B', models.CharField(blank=True, max_length=100, null=True)),
                ('over_caution_ingredient_code_B', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_medicine_code_B', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_medicine_name_B', models.CharField(blank=True, max_length=100, null=True)),
                ('over_caution_manufacturer_name_B', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_pay_B', models.CharField(blank=True, max_length=5, null=True)),
                ('over_caution_pbc_no', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_pbc_dt', models.CharField(blank=True, max_length=30, null=True)),
                ('over_caution_note', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='pregnat_ban',
            name='pregnat_pay',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='pregnat_ban',
            name='pregnat_pbc_dt',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pregnat_ban',
            name='pregnat_pbc_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pregnat_ban',
            name='pregnat_version',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
