# Generated by Django 2.0 on 2020-06-15 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0003_auto_20200615_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
