# Generated by Django 2.1.5 on 2020-06-15 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0004_auto_20200615_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='prescription_photo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
