# Generated by Django 2.1.5 on 2020-06-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0005_prescription_prescription_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='date_of_dosing',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='disease_code',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='medicine_name',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='number_of_dosing',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='taking_method',
        ),
        migrations.AddField(
            model_name='medicine',
            name='change_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='chart',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='class_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='class_no',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='color_back',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='color_front',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_shape',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='edi_code',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='entp_seb',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='etc_otc_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='form_code_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='img_regist_ts',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='item_eng_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='item_image',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='item_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='item_permit_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='item_seq',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='leng_long',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='leng_short',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='line_back',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='line_front',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_back',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_back_anal',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_back_img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_front',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_front_anal',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='mark_code_front_img',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='print_back',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='print_pront',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='thick',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
