# Generated by Django 2.1.5 on 2020-06-15 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0006_auto_20200615_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='entp_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
