# Generated by Django 2.1.7 on 2020-06-16 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0008_auto_20200615_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='pre_medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Prescription'),
        ),
    ]
