# Generated by Django 2.1.5 on 2020-06-16 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0009_medicine_pre_medicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(blank=True, max_length=30, null=True)),
                ('disease_code', models.CharField(blank=True, max_length=30, null=True)),
                ('disease_prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Prescription')),
            ],
        ),
    ]
