# Generated by Django 2.1.5 on 2020-06-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0010_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='prescription_date',
            field=models.DateTimeField(null=True),
        ),
    ]
