# Generated by Django 2.1.5 on 2020-06-16 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0011_auto_20200616_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='disease_prescription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disease', to='health_bot.Prescription'),
        ),
    ]
