# Generated by Django 2.1.7 on 2020-06-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0012_auto_20200616_2231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Open_Efficacy_group_overlap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_code', models.CharField(blank=True, max_length=30, null=True)),
                ('item_seq', models.CharField(blank=True, max_length=30, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('efficacy_medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Open_over_ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_code', models.CharField(blank=True, max_length=30, null=True)),
                ('ingr_kor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ingr_eng_name', models.CharField(blank=True, max_length=30, null=True)),
                ('item_seq', models.CharField(blank=True, max_length=30, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_ingr_code', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_ingr_kor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_ingr_eng_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_item_seq', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('mixture_class_name', models.CharField(blank=True, max_length=30, null=True)),
                ('prohbt_content', models.CharField(blank=True, max_length=200, null=True)),
                ('over_medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine')),
            ],
        ),
        migrations.CreateModel(
            name='Open_pregnat_ban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingr_code', models.CharField(blank=True, max_length=30, null=True)),
                ('ingr_kor_name', models.CharField(blank=True, max_length=30, null=True)),
                ('ingr_eng_name', models.CharField(blank=True, max_length=30, null=True)),
                ('item_seq', models.CharField(blank=True, max_length=30, null=True)),
                ('item_name', models.CharField(blank=True, max_length=30, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('prohbt_content', models.CharField(blank=True, max_length=200, null=True)),
                ('pregnat_medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine')),
            ],
        ),
    ]
