# Generated by Django 2.1.7 on 2020-06-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0013_open_efficacy_group_overlap_open_over_ban_open_pregnat_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='open_efficacy_group_overlap',
            name='efficacy_medicine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine'),
        ),
        migrations.AlterField(
            model_name='open_over_ban',
            name='over_medicine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine'),
        ),
        migrations.AlterField(
            model_name='open_pregnat_ban',
            name='pregnat_medicine',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='health_bot.Medicine'),
        ),
    ]
