# Generated by Django 2.1.7 on 2020-06-19 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0014_auto_20200618_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Open_Efficacy_group_overlap',
            new_name='OpenEfficacyGroupOverlap',
        ),
        migrations.RenameModel(
            old_name='Open_over_ban',
            new_name='OpenOverBan',
        ),
        migrations.RenameModel(
            old_name='Open_pregnat_ban',
            new_name='OpenPregnatBan',
        ),
    ]
