# Generated by Django 2.1.5 on 2020-08-17 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0015_auto_20200619_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='family_name',
        ),
        migrations.AddField(
            model_name='family',
            name='user_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='health_bot.User'),
        ),
    ]
