# Generated by Django 2.2 on 2020-08-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0016_auto_20200817_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='family_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
