# Generated by Django 2.2 on 2020-08-21 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0017_user_family_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='user_family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='family_name',
        ),
        migrations.CreateModel(
            name='FamilyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='health_bot.Family')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='health_bot.User')),
            ],
        ),
    ]
