# Generated by Django 2.2 on 2020-08-21 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0018_auto_20200822_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='familylist',
            name='family_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='family_user', to='health_bot.User'),
        ),
    ]
