# Generated by Django 2.2 on 2020-08-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0019_familylist_family_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='health_bot.User'),
        ),
    ]
