# Generated by Django 2.2 on 2020-08-21 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health_bot', '0021_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='family_user_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='family_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='noti_family_user', to='health_bot.User'),
        ),
    ]
